#!/bin/bash -xv

###############################################################################
# The immediately following definitions are constant for a particular version
export PROJECT_NAME=libzmq
export PROJECT_VERSION=4.3.0
export JIRA_RELEASE=BUS-1778           # release artifact in jira

#
export CMAKE_VERSION=2.8.12.2
